grpc:
  client:
    user-service:
      negotiationType: tls
      security:
        trustCertCollection: file:C:\\Users\\arnab.shil\\IdeaProjects\\gRPC-flix-new\\ssl\\user-service\\ca.cert.pem
    movie-service:
      negotiationType: tls
      security:
        trustCertCollection: file:C:\\Users\\arnab.shil\\IdeaProjects\\gRPC-flix-new\\ssl\\movie-service\\ca.cert.pem

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: "aggregator-service"

debug: true